apiVersion: v1
kind: Service
metadata:
  name: nexus-server
  namespace: nexus
spec:
  selector:
    app: nexus-server
  type: ClusterIP
  ports:
    -
      name: nexus-registry
      port: 8081
      protocol: TCP
      targetPort: 8081
