apiVersion: v1
kind: Service
metadata:
  name: nexus-server
  namespace: nexus
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  ingressClassName: nginx
  rules:
  - host: nexus.local
    http:
      paths:
      - backend:
          service:
            name: nexus-server
            port:
              number: 8081
        path: /
        pathType: Prefix
  - host: nexus.summtech.in
    http:
      paths:
      - backend:
          service:
            name: nexus-server
            port:
              number: 8081
        path: /
        pathType: Prefix
