version: '3.9' 
services: 
    ipadvogados: 
      image: 'ghcr.io/fernandogomesdf/ipadvogados:latest'
      ports: 
        - :4000

networks:
    default:
        external:
            name: my_attachable_network