name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Build Angular
      run: npm install && npm run build
    
    - 
      name: Log into registry
        uses: docker/login-actionv1.14.1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - 
      name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            version=latest
          tags: ${{ env.IMAGE_NAME }}:latest

      
    
  
      
